apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 2
  selector:
    matchLabels:
      module: login
      app: ms-k8s
  template:
    metadata:
      labels:
        module: login
        app: ms-k8s
    spec:
      containers:
      - name: login
        image: oldhu/login-service
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
      dnsPolicy: ClusterFirst
